#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTFILES=$HOME/.dotfiles
DOTFZF=$HOME/.fzf
DOTLOCAL=$HOME/.local/share/dotfiles

GITCLONE="git clone --depth=1"

cd "$HOME" || exit
rm -rf "$DOTFILES"
mkdir "$DOTFILES"
cd "$DOTFILES" || exit

git init
git remote add origin https://github.com/tylersmalley/dotfiles.git
git pull origin master

# Swap origin so I can make edits easily
git remote rm origin
git remote add origin git@github.com:tylersmalley/dotfiles.git

rm -rf \
  "$DOTFZF" \
  "$DOTLOCAL" \
  "$HOME/.bashrc" \
  "$HOME/.gitconfig" \
  "$HOME/.vim" \
  "$HOME/.vimrc" \
  "$HOME/.zshrc"

mkdir -p \
  "$DOTLOCAL" \
  "$HOME/.local/share/vim/{swap,undo}" \
  "$HOME/.vim/colors" \
  "$HOME/.vim/pack/plugins/start"

ln -s "$DOTFILES/bashrc" "$HOME/.bashrc"
ln -s "$DOTFILES/gitconfig" "$HOME/.gitconfig"
ln -s "$DOTFILES/vimrc" "$HOME/.vimrc"
ln -s "$DOTFILES/zshrc" "$HOME/.zshrc"

$GITCLONE https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

# $GITCLONE https://github.com/junegunn/fzf.git "$DOTFZF"
# "$DOTFZF/install" --key-bindings --completion --no-update-rc

# ZSHPLUGS=(
#   "zsh-completions"
#   "zsh-history-substring-search"
#   "zsh-syntax-highlighting"
# )

# for INDEX in ${!ZSHPLUGS[*]}; do
#   ZSHPLUG="${ZSHPLUGS[$INDEX]}"
#   $GITCLONE "https://github.com/zsh-users/$ZSHPLUG.git" "$DOTLOCAL/$ZSHPLUG"
# done

# VIMPLUGS=(
#   "w0rp/ale"
#   "editorconfig/editorconfig-vim"
#   "junegunn/fzf.vim"
#   "sheerun/vim-polyglot"
#   "jelera/vim-javascript-syntax"
#   "Quramy/vim-js-pretty-template"
#   "StanAngeloff/php.vim"
# )

# for INDEX in ${!VIMPLUGS[*]}; do
#   VIMPLUG="${VIMPLUGS[$INDEX]}"
#   PLUGDIR=$(echo "$VIMPLUG" | cut -d '/' -f2)

#   $GITCLONE "https://github.com/$VIMPLUG.git" "$HOME/.vim/pack/plugins/start/$PLUGDIR"
# done

wget https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim -P "$HOME/.vim/colors/"

# cd "$HOME" || exit
# rm -f "${HOME}/.zcompdump*"
